#include "exporter.h"
#include <sstream>
#include <fstream>
#include <iomanip>

namespace samp_editor {

std::string PawnExporter::ExportToString(const std::vector<const EditorObject*>& objects, ExportFormat format) {
    std::stringstream ss;
    ss << std::fixed << std::setprecision(4);

    ss << "// =========================================================\n";
    ss << "// Generated by SA-MP Android Native Map Editor\n";
    ss << "// Total Objects: " << objects.size() << "\n";
    ss << "// =========================================================\n\n";

    if (format == ExportFormat::CreateDynamicObject_Streamer) {
        ss << "#include <a_samp>\n";
        ss << "#include <streamer>\n\n";
        ss << "public OnFilterScriptInit()\n";
        ss << "{\n";
        for (const auto* objPtr : objects) {
            if (!objPtr) continue;
            const auto& obj = *objPtr;
            ss << "    CreateDynamicObject("
               << obj.modelId << ", "
               << obj.position.x << ", " << obj.position.y << ", " << obj.position.z << ", "
               << obj.rotationEuler.x << ", " << obj.rotationEuler.y << ", " << obj.rotationEuler.z << ", "
               << obj.worldId << ", " << obj.interiorId << ", -1, "
               << obj.streamDistance << ", " << obj.drawDistance << ");";
            if (!obj.name.empty()) {
                ss << " // " << obj.name;
            }
            ss << "\n";
        }
        ss << "    return 1;\n";
        ss << "}\n";
    } else if (format == ExportFormat::CreateObject_Standard) {
        ss << "#include <a_samp>\n\n";
        ss << "public OnFilterScriptInit()\n";
        ss << "{\n";
        for (const auto* objPtr : objects) {
            if (!objPtr) continue;
            const auto& obj = *objPtr;
            ss << "    CreateObject("
               << obj.modelId << ", "
               << obj.position.x << ", " << obj.position.y << ", " << obj.position.z << ", "
               << obj.rotationEuler.x << ", " << obj.rotationEuler.y << ", " << obj.rotationEuler.z << ", "
               << obj.drawDistance << ");";
            if (!obj.name.empty()) {
                ss << " // " << obj.name;
            }
            ss << "\n";
        }
        ss << "    return 1;\n";
        ss << "}\n";
    } else {
        ss << "modelid,posX,posY,posZ,rotX,rotY,rotZ\n";
        for (const auto* objPtr : objects) {
            if (!objPtr) continue;
            const auto& obj = *objPtr;
            ss << obj.modelId << ","
               << obj.position.x << "," << obj.position.y << "," << obj.position.z << ","
               << obj.rotationEuler.x << "," << obj.rotationEuler.y << "," << obj.rotationEuler.z << "\n";
        }
    }

    return ss.str();
}

std::string PawnExporter::ExportToString(const std::vector<std::unique_ptr<EditorObject>>& objects, ExportFormat format) {
    std::vector<const EditorObject*> ptrs;
    ptrs.reserve(objects.size());
    for (const auto& o : objects) {
        if (o) ptrs.push_back(o.get());
    }
    return ExportToString(ptrs, format);
}

std::string PawnExporter::ExportToString(const std::vector<EditorObject>& objects, ExportFormat format) {
    std::vector<const EditorObject*> ptrs;
    ptrs.reserve(objects.size());
    for (const auto& o : objects) {
        ptrs.push_back(&o);
    }
    return ExportToString(ptrs, format);
}

bool PawnExporter::ExportToFile(const std::string& filePath, const std::vector<std::unique_ptr<EditorObject>>& objects, ExportFormat format) {
    std::ofstream file(filePath);
    if (!file.is_open()) return false;

    file << ExportToString(objects, format);
    return true;
}

} // namespace samp_editor
